name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  # 允许手动触发
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # 👇 下面这一行需要你稍微修改一下！
        run: git push --force https://Guolicen:$HF_TOKEN@huggingface.co/spaces/Guolicen/Openclawoen main
